globalvar renk1;
renk1=c_lime;
globalvar renk2;
renk2=c_yellow;
globalvar renk3;
renk3=c_red;
globalvar renk4;
renk4=c_blue;
globalvar g1;
globalvar g2;
globalvar g3;
globalvar g4;
globalvar g5;
globalvar g6;
g1=Lupikan;
g2=Myython;
g3=Lidd;
g4=Krothonias;
g5=Kythoness;
g6=Niddony;
globalvar g1_renk;
globalvar g2_renk;
globalvar g3_renk;
globalvar g4_renk;
globalvar g5_renk;
globalvar g6_renk;
g1_renk=renk1;
g2_renk=renk2;
g3_renk=renk3;
g4_renk=renk3;
g5_renk=renk4;
g6_renk=renk4;